services:
  data-governance-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-governance-demo
    command: "bash run-all.sh"
    depends_on:
      mongodb:
        condition: service_started
      neo4j:
        condition: service_started

  mongodb:
    image: mongo:9
    container_name: mongodb
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
