services:
  data-governance-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-governance-demo
    volumes:
      - .:/home
    command: "bash run-all.sh"
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
