services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo
    volumes:
      - .:/home
    command: "bash run-all.sh"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"