name: Docker Compose CI

on:
  push:
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-cached-tools: 'true'
          remove-codeql: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose
        run: |
          find . -type f -name "*.sh" -exec chmod +x {} \;
          ./init.sh
          docker-compose --env-file ./config/myenvfile.env up --build --abort-on-container-exit
